// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistemadeventas_AlmacenMera.Data;

#nullable disable

namespace Sistemadeventas_AlmacenMera.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_almacen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_entrada")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.HasKey("IdAlmacen")
                        .HasName("PK__almacen__098D5D13B1E3EE71");

                    b.HasIndex("IdProducto");

                    b.ToTable("almacen", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("IdCategoria")
                        .HasName("PK__categori__CD54BC5A783E9B06");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle")
                        .HasName("PK__detalle___4F1332DED72C0490");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("detalle_ventas", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Fiado", b =>
                {
                    b.Property<int>("IdFiado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fiado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiado"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("MontoPagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("monto_pagado");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("saldo_pendiente");

                    b.HasKey("IdFiado")
                        .HasName("PK__fiados__420FD58DC3369324");

                    b.HasIndex("IdVenta");

                    b.ToTable("fiados", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialEntradasSalida", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime?>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_movimiento")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdHistorial")
                        .HasName("PK__historia__76E6C5028A10B7E2");

                    b.HasIndex("IdProducto");

                    b.ToTable("historial_entradas_salidas", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialPrecio", b =>
                {
                    b.Property<int>("IdPrecio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_precio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrecio"));

                    b.Property<DateTime?>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("IdPrecio")
                        .HasName("PK__historia__A70EF6EDD3220AF5");

                    b.HasIndex("IdProducto");

                    b.ToTable("historial_precios", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialVentasUsuario", b =>
                {
                    b.Property<int>("IdHistorialVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialVenta"));

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_venta");

                    b.HasKey("IdHistorialVenta")
                        .HasName("PK__historia__B96FB70281153004");

                    b.HasIndex("IdVenta");

                    b.ToTable("historial_ventas_usuario", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.PagosFiado", b =>
                {
                    b.Property<int>("IdPagoFiado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago_fiado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPagoFiado"));

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdFiado")
                        .HasColumnType("int")
                        .HasColumnName("id_fiado");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_pago");

                    b.HasKey("IdPagoFiado")
                        .HasName("PK__pagos_fi__CDDE6AE73CCAB987");

                    b.HasIndex("IdFiado");

                    b.ToTable("pagos_fiados", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto")
                        .HasName("PK__producto__FF341C0D2E6180F9");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProveedor");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Proveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_proveedor");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("PK__proveedo__8D3DFE28D6467724");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol")
                        .HasName("PK__roles__6ABCB5E03EFACA1E");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("activo")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario")
                        .HasName("PK__usuarios__4E3E04AD5D8725D1");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Email" }, "UQ__usuarios__AB6E6164A612CDC6")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);

                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_venta")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoVenta")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("contado")
                        .HasColumnName("tipo_venta");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdVenta")
                        .HasName("PK__ventas__459533BF50DF49F8");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Almacen", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Producto", "IdProductoNavigation")
                        .WithMany("Almacens")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__almacen__id_prod__49C3F6B7");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.DetalleVenta", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__detalle_v__id_pr__5535A963");

                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__detalle_v__id_ve__5441852A");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Fiado", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Venta", "IdVentaNavigation")
                        .WithMany("Fiados")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__fiados__id_venta__5FB337D6");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialEntradasSalida", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Producto", "IdProductoNavigation")
                        .WithMany("HistorialEntradasSalida")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__historial__id_pr__68487DD7");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialPrecio", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Producto", "IdProductoNavigation")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__historial__id_pr__59063A47");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.HistorialVentasUsuario", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Venta", "IdVentaNavigation")
                        .WithMany("HistorialVentasUsuarios")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__historial__id_ve__6C190EBB");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.PagosFiado", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Fiado", "IdFiadoNavigation")
                        .WithMany("PagosFiados")
                        .HasForeignKey("IdFiado")
                        .HasConstraintName("FK__pagos_fia__id_fi__6383C8BA");

                    b.Navigation("IdFiadoNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Producto", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__productos__id_ca__45F365D3");

                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK__productos__id_pr__44FF419A");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Usuario", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__usuarios__id_rol__3D5E1FD2");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Venta", b =>
                {
                    b.HasOne("Sistemadeventas_AlmacenMera.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__ventas__id_usuar__5165187F");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Fiado", b =>
                {
                    b.Navigation("PagosFiados");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Producto", b =>
                {
                    b.Navigation("Almacens");

                    b.Navigation("DetalleVenta");

                    b.Navigation("HistorialEntradasSalida");

                    b.Navigation("HistorialPrecios");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Proveedore", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Usuario", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Sistemadeventas_AlmacenMera.Models.Venta", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Fiados");

                    b.Navigation("HistorialVentasUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
